name: Deploy Recipe Edit Microservice

on:
  push:
    branches:
      - main
    paths:
      - 'recipe-edit-microservice/**'

jobs:
  deploy-recipe-edit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for recipe-edit-microservice
        run: |
          cd recipe-edit-microservice
          docker build -t ${{ secrets.DOCKER_USERNAME }}/recipe-edit-microservice .
          docker push ${{ secrets.DOCKER_USERNAME }}/recipe-edit-microservice:latest

      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST_RECIPE_EDIT }} << 'EOF'
            docker stop recipe-edit-microservice || true
            docker rm recipe-edit-microservice || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/recipe-edit-microservice:latest
            docker run -d -p 6002:6002 --name recipe-edit-microservice \
              -e DB_RECIPES_HOST=${{ secrets.DB_RECIPES_HOST }} \
              -e DB_RECIPES_NAME=${{ secrets.DB_RECIPES_NAME }} \
              -e DB_RECIPES_USER=${{ secrets.DB_RECIPES_USER }} \
              -e DB_RECIPES_PASS=${{ secrets.DB_RECIPES_PASS }} \
              ${{ secrets.DOCKER_USERNAME }}/recipe-edit-microservice:latest
          EOF
